---
# Global variables

tld: "{{ tld_param | default('example.com') }}"
exchange_dir: "{{ exchange_dir_param | default('/exchange') }}"
home_dir: "{{ home_dir_param | default('home') }}"

## Host
app_directory: "jupyterhub4education"
working_dir: "{{ ansible_env.PWD }}/{{ app_directory }}"

# End-user account info
org_name: "{{ org_name_param | default('myedu') }}"
course_id: "{{ course_id_param | default('intro101') }}"
grader_group: "{{ grader_group_param | default('formgrade-') }}{{ course_id }}"
student_group: "{{ student_grp_param | default('nbgrader-') }}{{ course_id }}"

# LTI 1.1 credentials
lti_consumer_key: "{{ lti_consumer_key_param | default('') }}"
lti_shared_secret: "{{ lti_shared_secret_param | default('') }}"

## Upstrem jupyterhub/jupyterhub and jupyter/docker-stacks hash commits
# https://github.com/jupyter/docker-stacks/commit/e00fd05364dffa4f0547498afe16d9a35f7f0eef
git_nb_hash_commit: "{{ git_nb_hash_commit_param | default('e00fd05364dffa4f0547498afe16d9a35f7f0eef') }}"
# https://github.com/jupyterhub/jupyterhub/commit/65de8c49167738fde9d7e88245593301a2a6a42a
git_jhub_hash_commit: "{{ git_jhub_hash_commit_param | default('22f86ad76c437d37bc26c28d9fecfa5457ef5974') }}"

## Configs
jupyter_notebook_config_source: "{{ jupyter_notebook_config_source_param | default('jupyter_notebook_config.py') }}"
jupyter_notebook_config_destination: "{{ jupyterhub_config_destination_param | default('/etc/jupyter/jupyter_notebook_config.py') }}"
jupyterhub_config_source: "{{ jupyterhub_config_source_param | default('jupyterhub_config.py') }}"
jupyterhub_config_destination: "{{ jupyterhub_config_destination_param | default('/etc/jupyterhub/jupyterhub_config.py') }}"

## Nbgrader configs
global_nbgrader_config_source: "{{ global_nbgrader_config_param | default('global_nbgrader_config') }}"
grader_course_nbgrader_config_source: "{{ grader_course_nbgrader_config_param | default('grader_course_nbgrader_config') }}"
grader_nbgrader_config_source: "{{ grader_nbgrader_config_param | default('grader_nbgrader_config.py') }}"

## Docker
# dockerfiles
docker_jupyterhub_base_dockerfile: "{{ docker_jupyterhub_base_dockerfile_param | default('Dockerfile.jhub') }}"
docker_notebook_base_dockerfile: "{{ docker_notebook_base_dockerfile_param | default('Dockerfile.base') }}"
docker_notebook_learner_dockerfile: "{{ docker_notebook_learner_dockerfile_param | default('Dockerfile.learner') }}"
docker_notebook_instructor_dockerfile: "{{ docker_notebook_instructor_dockerfile_param | default('Dockerfile.instructor') }}"
docker_notebook_grader_dockerfile: "{{ docker_notebook_grader_dockerfile_param | default('Dockerfile.grader') }}"

# docker-compose yaml
docker_dc_yml: "{{ docker_dc_yml_param | default('docker-compose.yml') }}"
docker_net: "{{ docker_net_param | default('jupyter-network') }}"
docker_domain: "{{ docker_domain_param | default('mydomain.local') }}"
docker_socket_host: "{{ docker_socket_host_param | default('/var/run/docker.sock') }}"
docker_socket_container: "{{ docker_socket_container_param | default('/var/run/docker.sock') }}"
docker_socket_container_permissions: "{{ docker_socket_container_permissions_param | default('rw') }}"
docker_socket_mount: "{{ docker_socket_host }}:{{ docker_socket_container }}:{{ docker_socket_container_permissions }}"

# notebook source image - used as base layer for base notebook image
docker_notebook_hash_commit: "{{ git_nb_hash_commit[0:12] }}"
docker_notebook_base_image: "{{ docker_notebook_base_image_param | default('jupyter/datascience-notebook:') }}{{ docker_notebook_hash_commit }}"
docker_jhub_hash_commit: "{{ git_jhub_hash_commit[0:12] }}"
docker_jhub_base_image: "{{ docker_jhub_base_image_param | default('jupyterhub/jupyterhub:1.2.0dev') }}"

# reverse proxy images
docker_chp_base_image: "{{ docker_chp_base_image_param | default('jupyterhub/configurable-http-proxy:4.2.0') }}"
docker_custom_jhub_image: "{{ docker_custom_jhub_image_param | default('custom/jupyterhub:base-') }}{{ docker_jhub_hash_commit }}"

# custom notebooks base and custom images
docker_custom_notebook_base_image: "{{ docker_custom_notebook_base_image_param | default('custom/datascience-notebook:base-') }}{{ docker_notebook_hash_commit }}"
docker_custom_notebook_learner_image: "{{ docker_custom_notebook_learner_image_param | default('custom/notebook:learner') }}-{{ docker_notebook_hash_commit }}"
docker_custom_notebook_grader_image: "{{ docker_custom_notebook_grader_image_param | default('custom/notebook:grader') }}-{{ org_name }}-{{ course_id }}-{{ docker_notebook_hash_commit }}"
docker_custom_notebook_instructor_image: "{{ docker_custom_notebook_instructor_image_param | default('custom/notebook:instructor') }}-{{ docker_notebook_hash_commit }}"

# configurable http proxy image
docker_chp_image: "{{ docker_chp_image_param | default('jupyterhub/configurable-http-proxy:4.2.0') }}"

# setup course image and container name
docker_setup_course_image: "{{ docker_setup_course_image_param | default('custom/setup-course') }}"

# jupyterhub, proxy, and grader service external and internal ports
docker_grader_ext_service_port: "{{ docker_grader_ext_service_port_param | default('9999') }}"
docker_grader_int_service_port: "{{ docker_grader_int_service_port_param | default('8888') }}"

# default chp port
docker_proxy_ext_proxy_port: "{{ docker_proxy_ext_proxy_port_param | default('8000') }}"
docker_proxy_int_proxy_port: "{{ docker_proxy_int_proxy_port_param | default('8001') }}"

# default setup course port
docker_setup_course_port: "{{ docker_setup_course_port_param | default('8000') }}"

# jupyterhub api port (when working with chp)
docker_jhub_ext_api_port: "{{ docker_jhub_ext_api_port_param | default('8081') }}"
docker_jhub_int_api_port: "{{ docker_jhub_int_api_port_param | default('8081') }}"

# jupyterhub env file
docker_jhub_env_file: "{{ docker_jhub_env_file_param | default('env.jhub') }}"

# grader service env file
docker_service_env_file: "{{ docker_jhub_env_file_param | default('env.service') }}"

# setup course env file
docker_setup_course_env_file: "{{ docker_setup_course_env_file_param | default('env.setup_course') }}"

# container/service names
docker_jhub_service_name: "{{ docker_jhub_service_name_param | default('jupyterhub') }}"

# grader service name
docker_grader_service_name: "{{ course_id }}"

# chp service name
docker_chp_service_name: "{{ docker_chp_service_name_param | default('chp') }}"

# setup course service name
docker_setup_course_service_name: "{{ docker_setup_course_service_name_param | default('setup-course') }}"

## Jupyterhub
# jupyterhub configs and routes
jhub_root: "{{ jhub_service_url_param | default('/srv/jupyterhub') }}"
jhub_api_path: "{{ jhub_api_path_param | default('hub/api') }}"
jhub_base_url: "{{ jhub_base_url_param | default('https://') }}{{ org_name }}.{{ tld }}/"
jhub_api_url: "{{ jhub_api_url_param | default('http://') }}{{ docker_jhub_service_name }}:{{ docker_jhub_int_api_port }}/{{ jhub_api_path }}"
jhub_service_url: "{{ jhub_service_url_param | default('http://') }}{{course_id}}:{{docker_grader_int_service_port}}"
jhub_internal_url: "{{ jhub_url_internal_param | default('http://') }}{{ docker_jhub_service_name }}:{{ docker_jhub_int_api_port }}"
jhub_service_prefix: "{{ jhub_service_prefix_param | default('/services/') }}{{ course_id }}"
jhub_client_id: "{{ jhub_client_id_param | default('service-') }}{{ course_id }}"
jhub_config: "{{ jhub_config_param | default('jupyterhub_config.py') }}"

## Grader service
# service username (owns service's api token) and home path
grader_service_username: "{{ grader_service_username_param | default('service-') }}{{ course_id }}"
grader_username: "{{ grader_username_param | default('grader-') }}{{ course_id }}"

# grader permissions
grader_instructor_uid: "{{ grader_instructor_uid_param | default('10001') }}"
grader_gid: "{{ nfs_home_dir_gid }}"
grader_home: "{{ home_dir }}/{{ grader_username }}"

## Jupyter Notebook config
jupyter_notebook_config: "{{ jupyter_notebook_config_param | default('jupyter_notebook_config.py') }}"

## Nbgrader
# nbrader configuration files
nbgrader_global_config: "{{ nbgrader_global_config_param | default('global_nbgrader_config.py') }}"
nbgrader_grader_config: "{{ nbgrader_grader_config_param | default('grader_nbgrader_config.py') }}"
nbgrader_grader_course_config: "{{ nbgrader_grader_course_config_param | default('grader_course_nbgrader_config.py') }}"

# jupyter notebook home directory
jnb_dir: "{{ jnb_dir_param | default('/home/jovyan') }}"

# nbgrader directories
nbgrader_root: "{{ nbgrader_root_param | default('/srv/nbgrader') }}"
nbgrader_exch_dir: "{{ nbgrader_root }}{{ exchange_dir }}"
nbgrader_logs_file: "{{ nbgrader_logs_file_param | default('/var/log/nbgrader/nbgrader.log') }}"
nbgrader_log_int: "{{ nbgrader_log_int_param | default('50') }}"

# NFS / Host
nfs_root: "{{ nfs_root_param | default('/mnt') }}"
nfs_exch_dir: "{{ nfs_exch_dir_param | default('exchange') }}"
nfs_exch_dir_permissions: "{{ nfs_exch_dir_permissions_param | default('0777') }}"
nfs_exch_dir_owner: "{{ nfs_exch_dir_owner_param | default('0777') }}"
nfs_exch_dir_group: "{{ nfs_exch_dir_permissions_param | default('0777') }}"
nfs_org_dir_permissions: "{{ nfs_org_dir_permissions_param | default('0755') }}"
nfs_home_dir_permissions: "{{ nfs_home_dir_permissions_param | default('0755') }}"
nfs_home_dir_uid: "{{ nfs_home_dir_uid_param | default('1000') }}"
nfs_home_dir_gid: "{{ nfs_home_dir_gid_param | default('100') }}"

# For use with grader/course nbgrader_configs
nfs_grader_nbgrader_config_path: "{{ nfs_root }}/{{ org_name }}/{{ grader_home }}/.jupyter"
nfs_grader_course_nbgrader_config_path: "{{ nfs_root }}/{{ org_name }}/{{ grader_home }}/{{ course_id }}"
